
spring:
  application:
    name: "kafka-spring"

  kafka:
    bootstrap-servers: "localhost:9092"

logging:
  level:
    root: INFO

myapp:
  kafka:
    create-topics: true
    schema-registry: "http://localhost:8081"
