#Fri Sep 26 10:47:12 UTC 2025
micronaut:
  application:
    name: kafka-micronaut

  server:
    port: 8090

kafka:
  bootstrap:
    servers: "localhost:9092"

  producers:
    avro-client:
      key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value.serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      schema.registry.url: "http://localhost:8081"
  consumers:
    avro-listener:
      key.deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value.deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      schema.registry.url: "http://localhost:8081"
      specific.avro.reader: true
