spring.security.user.name=testlogin
spring.security.user.password=password
spring.security.user.roles=manager,admin,developer

spring.session.store-type=redis
spring.session.redis.namespace=sessioncommune::

spring.redis.host=localhost
spring.redis.password=
spring.redis.port=6379
